### ISSUE TITLE
Question on inserting an image to an existing paragraph

### ISSUE THREAD

**Issue by Yttr1umG** [gomutex/godocx#45]
Hello! I found the library useful but there's a question on image inserting. 
`document.AddPicture`  is an available method but when I use it, it wil create a new paragraph. If there's any way to insert an inline image to an existing paragraph? 

Thanks for the help!

**Comment by gomutex** [comment]
There is no direct API for it at the moment. But i can look into it. Can you provide example docx file?

**Comment by Yttr1umG** [comment]
[example docx.docx](https://github.com/user-attachments/files/16620766/example.docx.docx)
Sure! Thanks a lot for your help!

**Comment by gomutex** [comment]
You can use the version v0.1.5 (or above) and use the following code:

```go
	// Add in existing paragraph
	p := document.AddParagraph("Hello ")
	p.AddPicture("gopher.png", units.Inch(1), units.Inch(1))
```
